version: '3.8'

services:
  postgres:
    container_name: sbsaas_postgre
    build: ./db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - sbsaas_postgres_data:/var/lib/postgresql/data
    networks:
      sbsaas-internal-network:
        ipv4_address: 172.28.0.10
    restart: unless-stopped

  minio1:
    image: minio/minio:latest
    container_name: sbsaas_minio1
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - TZ=${TZ}
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - sbsaas_minio_data:/data
    networks:
      sbsaas-internal-network:
        ipv4_address: 172.28.0.21
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  clamav:
    image: clamav/clamav:latest
    container_name: sbsaas_clamav
    ports:
      - "${CLAMAV_PORT}:3310"
    volumes:
      - sbsaas_clamav_db:/var/lib/clamav
    networks:
      sbsaas-internal-network:
        ipv4_address: 172.28.0.30
      sbsaas-public-network:
        ipv4_address: 172.29.0.30
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "clamdscan", "--version"]
      interval: 1m
      timeout: 30s
      retries: 3

  api:
    container_name: sbsaas_api
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "${API_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=${TZ}
      # Connection strings and other secrets should be passed here
      # Example:
      # - ConnectionStrings__DefaultConnection=Host=172.28.0.10;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      # - Minio__Endpoint=http://172.28.0.21:9000
      # - Clamav__Host=172.28.0.30
      # - Clamav__Port=3310
    networks:
      sbsaas-internal-network:
        ipv4_address: 172.28.0.40
      sbsaas-public-network:
        ipv4_address: 172.29.0.40
    depends_on:
      postgres:
        condition: service_started
      minio1:
        condition: service_healthy
      clamav:
        condition: service_healthy
    restart: unless-stopped

volumes:
  sbsaas_postgres_data:
    driver: local
  sbsaas_minio_data:
    driver: local
  sbsaas_clamav_db:
    driver: local

networks:
  sbsaas-internal-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
  sbsaas-public-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24