version: '3.8'

services:
  postgres:
    image: sbsaas/postgres:17withtsgisagent
    container_name: sbsaas_postgres
    build: .
    env_file:
      - postgres.env
    command: postgres -c shared_preload_libraries='timescaledb'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - sbsaas_postgres_data:/var/lib/postgresql/data
    networks:
      sbsaas-internal-network:
        ipv4_address: 172.28.0.10
    restart: unless-stopped

volumes:
  sbsaas_postgres_data:
    driver: local
networks:
  sbsaas-internal-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
